# Generated by Django 3.2.16 on 2023-01-17 15:29

from django.db import migrations


def forwards_func(apps, schema_editor):
    # Get model
    Courses = apps.get_model("mainapp", "Courses")
    # Create model's objects
    Courses.objects.create(
        name="Web Python",
        description="Курс Web Python поможет Вам осовоить язык программирования Python, а также разобраться с его "
        "основными аспектами, такими как: модули, парсеры, регулярные выражения. Курс поможет Вам "
        "научиться составлять эффективные программы для решения Ваших задач и проблем. Он научит Вас "
        "создавать собственные веб-приложения для работы с базами данных и сайтами. Вы сможете "
        "использовать Python для изучения Java, Ruby, PHP, C, C ++, C # или любого другого языка "
        "программирования.\r\nНа курсе Web Python проходит изучение веб-фреймворков Django, Bootstrap и "
        "Flask.\r\nВо втором семестре вы изучите такие инструменты и методы, как:\r\n\r\n* PHP и "
        "MySql;\r\n* Работа с файлами DOC, EXCEL, PATH;\r\n* Реляционная и объектная модель базы "
        "данных;\r\n* Создание и управление пакетами;\r\n* Как работать с FTP сервером;\r\n* Настройка "
        "среды и создание сайтов;\r\n* Веб-серверы;\r\n* Конфигурационное управление в Unix и "
        "Windows;\r\n* Инструменты для создания сайта;\r\n* Интеграция внешних приложений;\r\n* "
        "Расширения;",
        description_as_markdown=True,
        cost=10000.50,
    )
    Courses.objects.create(
        name="Web Golang",
        description="На курсе Web Golang вы изучите основы Go, получите практические навыки реализации проектов на "
        "Golang и научитесь работать в распределенных средах разработки. Вы узнаете: что такое Go как "
        "компилировать код Go как писать тесты как работает веб-сервер. Курс ведет Виктор "
        "Иванов\r\nСертифицированный специалист Google Developer Expert (Certified Technical "
        "Professional).\r\nАвтор учебника “Web-разработка на Go”. На курсе вы будете изучать основы языка "
        "программирования Go и получите практический опыт реализации проектов на Go.",
        description_as_markdown=True,
        cost=9009.99,
    )
    Courses.objects.create(
        name="Web JavaScript",
        description="Курс JavaScript ведёт преподаватель Дмитрий Кокшаров. Он преподает в разных вузах, в том числе и "
        "в МФТИ. Дмитрий считает, что курс — это база знаний, которая пригодится в жизни. \r\nКурс "
        "JavaScript состоит из модулей, один из которых — «Основы функционального программирования». Этот "
        "модуль рассчитан на тех, кто не знает основы JavaScript или только начал заниматься этим языком. "
        "Вы узнаете, как устроены функции, какие бывают типы данных, как применять модификаторы.\r\nНа "
        "курсе JavaScript Вы изучите:\r\n\r\n* Основные паттерны проектирования (design patterns) \r\n* "
        "Разработку на чистом JavaScript\r\n* ReactJS и AngularJS\r\n* ООП на JavaScript \r\n* Основы "
        "HTML 5 и CSS3\r\n* Javascript ES6 и ES7\r\n* Основы кроссбраузерные\r\n\r\nВы погрузитесь в "
        "динамичный мир современного JS-разработки, который станет интересным и увлекательным. Курс "
        "JavaScript будет полезен как новичкам, так и опытным разработчикам, желающим изучить новые "
        "технологии и получить новые знания.",
        description_as_markdown=True,
        cost=2500.15,
    )


def reverse_func(apps, schema_editor):
    # Get model
    Courses = apps.get_model("mainapp", "Courses")
    # Delete objects
    Courses.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_data_migration_News"),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
