# Generated by Django 3.2.16 on 2023-01-17 15:55

from django.db import migrations


def forwards_func(apps, schema_editor):
    Lesson = apps.get_model("mainapp", "Lesson")
    Lesson.objects.create(course_id=1, num=1, title="Lesson 1")
    Lesson.objects.create(course_id=1, num=2, title="Lesson 2")
    Lesson.objects.create(course_id=2, num=1, title="Lesson 1")
    Lesson.objects.create(course_id=2, num=2, title="Lesson 2")
    Lesson.objects.create(course_id=3, num=1, title="Lesson 1")
    Lesson.objects.create(course_id=3, num=2, title="Lesson 2")
    Lesson.objects.create(course_id=3, num=3, title="Lesson 3")


def reverse_func(apps, schema_editor):
    # Get model
    Lesson = apps.get_model("mainapp", "Lesson")
    # Delete objects
    Lesson.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0003_data_migration_Courses"),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
